/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fib.h"

int fibo(int n) {
	if(n == 0 || n == 1) return 1;
	else return fibo(n-1) + fibo(n-2);
}

int *
fib_1_svc(number *argp, struct svc_req *rqstp)
{
	static int  result = 0;
	int N;

	printf("The requested number : %d\n", argp->num);
	if(argp != NULL) {
		N = argp->num;
	
		// the fibonacci algorithm
		result = fibo(N);
	}

	printf("result : %d\n", result);
	return &result;
}
